// Industries options
export const Industries = [
  { label: "Accounting", value: "Accounting" },
  { label: "Aerospace", value: "Aerospace" },
  { label: "Aircraft", value: "Aircraft" },
  { label: "Airline", value: "Airline" },
  { label: "Agriculture", value: "Agriculture" },
  { label: "Advertising", value: "Advertising" },
  { label: "Automotive", value: "Automotive" },
  { label: "Apparel & Accessories", value: "Apparel & Accessories" },
  { label: "Biotechnology", value: "Biotechnology" },
  { label: "Brokerage", value: "Brokerage" },
  { label: "Call Centers", value: "Call Centers" },
  { label: "Cargo Handling", value: "Cargo Handling" },
  { label: "Chemical", value: "Chemical" },
  { label: "Consulting", value: "Consulting" },
  { label: "Computer", value: "Computer" },
  { label: "Consumer Products", value: "Consumer Products" },
  { label: "Cybersecurity", value: "Cybersecurity" },
  { label: "Cosmetics", value: "Cosmetics" },
  { label: "Department Stores", value: "Department Stores" },
  { label: "Education", value: "Education" },
  { label: "Electronics", value: "Electronics" },
  { label: "Energy", value: "Energy" },
  { label: "Entertainment & Leisure", value: "Entertainment & Leisure" },
  { label: "Executive Search", value: "Executive Search" },
  { label: "Financial Services", value: "Financial Services" },
  { label: "Food, Beverage & Tobacco", value: "Food, Beverage & Tobacco" },
  { label: "Fundraising", value: "Fundraising" },
  { label: "Grocery", value: "Grocery" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Hospitality", value: "Hospitality" },
  { label: "Internet Publishing", value: "Internet Publishing" },
  { label: "Investment Banking", value: "Investment Banking" },
  { label: "Legal", value: "Legal" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Motion Picture & Video", value: "Motion Picture & Video" },
  { label: "Music", value: "Music" },
  { label: "Newspaper Publishers", value: "Newspaper Publishers" },
  { label: "Defense", value: "Defense" },
  { label: "Nonprofit", value: "Nonprofit" },
  { label: "Online Auctions", value: "Online Auctions" },
  { label: "Pension Funds", value: "Pension Funds" },
  { label: "Pharmaceuticals", value: "Pharmaceuticals" },
  { label: "Private Equity", value: "Private Equity" },
  { label: "Broadcasting", value: "Broadcasting" },
  { label: "Publishing", value: "Publishing" },
  { label: "Real Estate", value: "Real Estate" },
  { label: "Retail & Wholesale", value: "Retail & Wholesale" },
  {
    label: "Securities & Commodity Exchanges",
    value: "Securities & Commodity Exchanges"
  },
  { label: "Service", value: "Service" },
  { label: "Soap & Detergent", value: "Soap & Detergent" },
  { label: "Banking", value: "Banking" },
  { label: "Software", value: "Software" },
  { label: "Sports", value: "Sports" },
  { label: "Technology", value: "Technology" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Television", value: "Television" },
  { label: "Transportation", value: "Transportation" },
  { label: "Trucking", value: "Trucking" },
  { label: "Venture Capital", value: "Venture Capital" }
];

export default {
  Industries
};
