// Tools options
export const Tools = [
  { label: "Adobe Acrobat", value: "Adobe Acrobat" },
  { label: "Adobe Bridge", value: "Adobe Bridge" },
  { label: "Adobe Dreamweaver", value: "Adobe Dreamweaver" },
  { label: "Adobe InDesign", value: "Adobe InDesign" },
  { label: "Adobe Lightroom", value: "Adobe Lightroom" },
  { label: "Adobe Muse", value: "Adobe Muse" },
  { label: "Adobe Premier", value: "Adobe Premier" },
  { label: "Adobe Social", value: "Adobe Social" },
  { label: "Avocode", value: "Avocode" },
  { label: "Buffer", value: "Buffer" },
  { label: "Canva", value: "Canva" },
  { label: "Cision", value: "Cision" },
  { label: "CMS", value: "CMS" },
  { label: "Constant Contact", value: "Constant Contact" },
  { label: "Consumer Barometer", value: "Consumer Barometer" },
  { label: "Contently", value: "Contently" },
  { label: "Copyscape", value: "Copyscape" },
  { label: "CoSchedule", value: "CoSchedule" },
  { label: "CrazyEgg", value: "CrazyEgg" },
  { label: "CSS", value: "CSS" },
  { label: "Delivra", value: "Delivra" },
  { label: "Drupal", value: "Drupal" },
  { label: "Emma", value: "Emma" },
  { label: "Adobe Photoshop", value: "Adobe Photoshop" },
  { label: "Facebook", value: "Facebook" },
  { label: "Github", value: "Github" },
  { label: "Google+", value: "Google+" },
  { label: "Google AdSense", value: "Google AdSense" },
  { label: "Google AdWords", value: "Google AdWords" },
  { label: "Google Alerts", value: "Google Alerts" },
  { label: "Google Analytics", value: "Google Analytics" },
  { label: "Google Drive", value: "Google Drive" },
  { label: "Google Keyword Planner", value: "Google Keyword Planner" },
  { label: "GetResponse", value: "GetResponse" },
  {
    label: "Google Keyword Research Tool",
    value: "Google Keyword Research Tool"
  },
  { label: "Google Search Console", value: "Google Search Console" },
  { label: "Google Trends", value: "Google Trends" },
  { label: "Adobe Illustrator", value: "Adobe Illustrator" },
  { label: "HARO", value: "HARO" },
  { label: "Hemingway Editor", value: "Hemingway Editor" },
  { label: "Hootsuite", value: "Hootsuite" },
  { label: "Hubspot", value: "Hubspot" },
  { label: "Instagram", value: "Instagram" },
  { label: "LeadPages", value: "LeadPages" },
  { label: "LinkedIn", value: "LinkedIn" },
  { label: "Macaw", value: "Macaw" },
  { label: "Magento", value: "Magento" },
  { label: "Adobe Creative Suite", value: "Adobe Creative Suite" },
  { label: "MailChimp", value: "MailChimp" },
  { label: "Marketo", value: "Marketo" },
  { label: "Medium", value: "Medium" },
  { label: "Microsoft Dynamics", value: "Microsoft Dynamics" },
  { label: "Microsoft Office", value: "Microsoft Office" },
  { label: "Adobe After Effects", value: "Adobe After Effects" },
  { label: "Microsoft Word", value: "Microsoft Word" },
  { label: "Moz", value: "Moz" },
  { label: "Open Office", value: "Open Office" },
  { label: "Optimizely", value: "Optimizely" },
  { label: "Pardot", value: "Pardot" },
  { label: "Pinterest", value: "Pinterest" },
  { label: "SalesLoft", value: "SalesLoft" },
  { label: "Screaming Frog", value: "Screaming Frog" },
  { label: "SEMrush", value: "SEMrush" },
  { label: "Sitecore", value: "Sitecore" },
  { label: "Snapchat", value: "Snapchat" },
  { label: "Sprout Social", value: "Sprout Social" },
  { label: "Squarespace", value: "Squarespace" },
  { label: "TagBoard", value: "TagBoard" },
  { label: "Salesforce Sales Cloud", value: "Salesforce Sales Cloud" },
  { label: "Thesaurus", value: "Thesaurus" },
  { label: "Tumblr", value: "Tumblr" },
  {
    label: "Salesforce Marketing Cloud",
    value: "Salesforce Marketing Cloud"
  },
  { label: "Tweetdeck", value: "Tweetdeck" },
  { label: "Twitter", value: "Twitter" },
  { label: "UXPin", value: "UXPin" },
  { label: "WebCEO", value: "WebCEO" },
  { label: "Whitespark.ca", value: "Whitespark.ca" },
  { label: "WordCounter", value: "WordCounter" },
  { label: "Unbounce", value: "Unbounce" },
  { label: "WordPress", value: "WordPress" },
  { label: "WordStream", value: "WordStream" },
  { label: "Wordtracker", value: "Wordtracker" },
  { label: "Xenu", value: "Xenu" },
  { label: "YEC", value: "YEC" },
  { label: "Yoast for WordPress", value: "Yoast for WordPress" }
];

export default {
  Tools
};
